<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录页</title>
    <link rel="stylesheet" type="text/css" href="<?= STATIC_PATH ?>css/normalize.css"/>
    <link rel="stylesheet" type="text/css" href="<?= STATIC_PATH ?>css/demo.css"/>
    <!--必要样式-->
    <link rel="stylesheet" type="text/css" href="<?= STATIC_PATH ?>css/component.css"/>
    <!--[if IE]>
    <script src="<?=STATIC_PATH?>js/html5.js"></script>
    <![endif]-->
</head>
<body>
<div class="container demo-1">
    <div class="content">
        <div id="large-header" class="large-header">
            <canvas id="demo-canvas"></canvas>
            <div class="logo_box">
                <h3>欢迎你</h3>
                <form action="" method="post" name="accountForm" id="accountForm">
                    <div class="input_outer">
                        <span class="username"></span>
                        <input name="logname" class="text" style="color: #FFFFFF !important" type="text" placeholder="请输入账号">
                    </div>
                    <div class="input_outer">
                        <span class="password"></span>
                        <input name="logpass" class="text" style="color: #FFFFFF !important; position:absolute; z-index:100;" value="" type="password" placeholder="请输入密码">
                    </div>
                    <div class="mb2"><a class="act-but submit" href="javascript:void(0);" style="color: #FFFFFF" id="account_submit">登录</a></div>
                </form>
            </div>
        </div>
    </div>
</div><!-- /container -->
<script src="<?= STATIC_PATH ?>js/jquery-1.8.3.min.js"></script>
<script src="<?= STATIC_PATH ?>js/TweenLite.min.js"></script>
<script src="<?= STATIC_PATH ?>js/EasePack.min.js"></script>
<script src="<?= STATIC_PATH ?>js/rAF.js"></script>
<script src="<?= STATIC_PATH ?>js/MouseMove.js"></script>
</body>
<script type="application/javascript">
    (function () {

    })();
</script>
</html>